-- ============================================================
-- Eco Compliance .NET — Migration manual
-- Equivalente a: dotnet ef database update
-- Executar no SQL Developer conectado como RM565199 em oracle.fiap.com.br
-- ============================================================

-- 1. Tabela de controle de migrations do EF Core
DECLARE v NUMBER; BEGIN
  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='__EFMigrationsHistory';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE "__EFMigrationsHistory" (
      "MigrationId"    NVARCHAR2(150) NOT NULL,
      "ProductVersion" NVARCHAR2(32)  NOT NULL,
      CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    )';
  END IF;
END;
/

-- 2. COMPANY (pode já existir do projeto Java)
DECLARE v NUMBER; BEGIN
  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='COMPANY';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE COMPANY (
      ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      NAME   VARCHAR2(255) NOT NULL,
      CNPJ   VARCHAR2(20),
      SECTOR VARCHAR2(100)
    )';
  END IF;
END;
/

-- 3. COMPLIANCE_RECORDS (pode já existir do projeto Java)
DECLARE v NUMBER; BEGIN
  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='COMPLIANCE_RECORDS';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE COMPLIANCE_RECORDS (
      ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      COMPANY_ID      NUMBER NOT NULL,
      COMPLIANCE_TYPE VARCHAR2(255) NOT NULL,
      STATUS          VARCHAR2(100) NOT NULL,
      REPORT_DATE     DATE NOT NULL,
      CONSTRAINT FK_CR_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID)
    )';
  END IF;
END;
/

-- 4. ESG_INDICATORS (nova tabela — só existe no projeto .NET)
DECLARE v NUMBER; BEGIN
  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='ESG_INDICATORS';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE ESG_INDICATORS (
      ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      COMPANY_ID     NUMBER NOT NULL,
      INDICATOR_TYPE VARCHAR2(100) NOT NULL,
      VALUE          BINARY_DOUBLE NOT NULL,
      UNIT           VARCHAR2(50),
      MEASURED_AT    DATE NOT NULL,
      CONSTRAINT FK_ESG_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID)
    )';
  END IF;
END;
/

-- 5. Índices
DECLARE v NUMBER; BEGIN
  SELECT COUNT(*) INTO v FROM user_indexes WHERE index_name='IX_COMPLIANCE_RECORDS_COMPANY_ID';
  IF v=0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IX_COMPLIANCE_RECORDS_COMPANY_ID ON COMPLIANCE_RECORDS(COMPANY_ID)'; END IF;
END;
/
DECLARE v NUMBER; BEGIN
  SELECT COUNT(*) INTO v FROM user_indexes WHERE index_name='IX_ESG_INDICATORS_COMPANY_ID';
  IF v=0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IX_ESG_INDICATORS_COMPANY_ID ON ESG_INDICATORS(COMPANY_ID)'; END IF;
END;
/

-- 6. Registrar migration no histórico do EF Core
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260613000001_InitialCreate', '8.0.10'
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM "__EFMigrationsHistory"
  WHERE "MigrationId" = '20260613000001_InitialCreate'
);
COMMIT;

-- 7. Verificar tabelas criadas
SELECT table_name FROM user_tables
WHERE table_name IN ('COMPANY','COMPLIANCE_RECORDS','ESG_INDICATORS','__EFMigrationsHistory')
ORDER BY table_name;
