using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EcoCompliance.API.Data.Migrations;

public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // Idempotent: cria cada tabela só se ainda não existir.
        // COMPANY e COMPLIANCE_RECORDS podem já existir do projeto Java.

        migrationBuilder.Sql(@"
DECLARE v NUMBER; BEGIN
  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='COMPANY';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE COMPANY (
      ID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      NAME   VARCHAR2(255) NOT NULL,
      CNPJ   VARCHAR2(20),
      SECTOR VARCHAR2(100)
    )';
  END IF;
END;");

        migrationBuilder.Sql(@"
DECLARE v NUMBER; BEGIN
  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='COMPLIANCE_RECORDS';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE COMPLIANCE_RECORDS (
      ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      COMPANY_ID      NUMBER NOT NULL,
      COMPLIANCE_TYPE VARCHAR2(255) NOT NULL,
      STATUS          VARCHAR2(100) NOT NULL,
      REPORT_DATE     DATE NOT NULL,
      CONSTRAINT FK_CR_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID)
    )';
  END IF;
END;");

        migrationBuilder.Sql(@"
DECLARE v NUMBER; BEGIN
  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='ESG_INDICATORS';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE ESG_INDICATORS (
      ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      COMPANY_ID     NUMBER NOT NULL,
      INDICATOR_TYPE VARCHAR2(100) NOT NULL,
      VALUE          BINARY_DOUBLE NOT NULL,
      UNIT           VARCHAR2(50),
      MEASURED_AT    DATE NOT NULL,
      CONSTRAINT FK_ESG_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID)
    )';
  END IF;
END;");

        migrationBuilder.Sql(@"
DECLARE v NUMBER; BEGIN
  SELECT COUNT(*) INTO v FROM user_indexes WHERE index_name='IX_COMPLIANCE_RECORDS_COMPANY_ID';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_COMPLIANCE_RECORDS_COMPANY_ID ON COMPLIANCE_RECORDS(COMPANY_ID)';
  END IF;
END;");

        migrationBuilder.Sql(@"
DECLARE v NUMBER; BEGIN
  SELECT COUNT(*) INTO v FROM user_indexes WHERE index_name='IX_ESG_INDICATORS_COMPANY_ID';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_ESG_INDICATORS_COMPANY_ID ON ESG_INDICATORS(COMPANY_ID)';
  END IF;
END;");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE ESG_INDICATORS");
        migrationBuilder.Sql("DROP TABLE COMPLIANCE_RECORDS");
        migrationBuilder.Sql("DROP TABLE COMPANY");
    }
}
