// <auto-generated />
using System;
using EcoCompliance.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoCompliance.API.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

        modelBuilder.Entity("EcoCompliance.API.Models.Company", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("NUMBER(19)")
                .HasColumnName("ID");

            b.Property<string>("Cnpj")
                .HasMaxLength(20)
                .HasColumnType("NVARCHAR2(20)")
                .HasColumnName("CNPJ");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("NVARCHAR2(255)")
                .HasColumnName("NAME");

            b.Property<string>("Sector")
                .HasMaxLength(100)
                .HasColumnType("NVARCHAR2(100)")
                .HasColumnName("SECTOR");

            b.HasKey("Id");
            b.ToTable("COMPANY");
        });

        modelBuilder.Entity("EcoCompliance.API.Models.ComplianceRecord", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("NUMBER(19)")
                .HasColumnName("ID");

            b.Property<long>("CompanyId")
                .HasColumnType("NUMBER(19)")
                .HasColumnName("COMPANY_ID");

            b.Property<string>("ComplianceType")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("NVARCHAR2(255)")
                .HasColumnName("COMPLIANCE_TYPE");

            b.Property<DateTime>("ReportDate")
                .HasColumnType("TIMESTAMP(7)")
                .HasColumnName("REPORT_DATE");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("NVARCHAR2(100)")
                .HasColumnName("STATUS");

            b.HasKey("Id");
            b.HasIndex("CompanyId");
            b.ToTable("COMPLIANCE_RECORDS");
        });

        modelBuilder.Entity("EcoCompliance.API.Models.EsgIndicator", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("NUMBER(19)")
                .HasColumnName("ID");

            b.Property<long>("CompanyId")
                .HasColumnType("NUMBER(19)")
                .HasColumnName("COMPANY_ID");

            b.Property<string>("IndicatorType")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("NVARCHAR2(100)")
                .HasColumnName("INDICATOR_TYPE");

            b.Property<DateTime>("MeasuredAt")
                .HasColumnType("TIMESTAMP(7)")
                .HasColumnName("MEASURED_AT");

            b.Property<string>("Unit")
                .HasMaxLength(50)
                .HasColumnType("NVARCHAR2(50)")
                .HasColumnName("UNIT");

            b.Property<double>("Value")
                .HasColumnType("BINARY_DOUBLE")
                .HasColumnName("VALUE");

            b.HasKey("Id");
            b.HasIndex("CompanyId");
            b.ToTable("ESG_INDICATORS");
        });

        modelBuilder.Entity("EcoCompliance.API.Models.ComplianceRecord", b =>
        {
            b.HasOne("EcoCompliance.API.Models.Company", "Company")
                .WithMany("ComplianceRecords")
                .HasForeignKey("CompanyId")
                .HasConstraintName("FK_CR_COMPANY")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Company");
        });

        modelBuilder.Entity("EcoCompliance.API.Models.EsgIndicator", b =>
        {
            b.HasOne("EcoCompliance.API.Models.Company", "Company")
                .WithMany("EsgIndicators")
                .HasForeignKey("CompanyId")
                .HasConstraintName("FK_ESG_COMPANY")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Company");
        });

        modelBuilder.Entity("EcoCompliance.API.Models.Company", b =>
        {
            b.Navigation("ComplianceRecords");
            b.Navigation("EsgIndicators");
        });
#pragma warning restore 612, 618
    }
}
